language: node_js

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - yarn install

script:
  - yarn test

deploy:
  provider: script
  script:
    - npm publish
  on:
    tags: true
